Guard against unicode when saving HDF5 imageseries
When writing out the [multiruby dexelas](https://github.com/HEXRD/examples/tree/master/NIST_ruby/multiruby_dexelas) example imageseries in hexrdgui after
performing aggregation, I would encounter the following error:

```
TypeError: No conversion path for dtype: dtype('<U3')
```

It appears that some of the metadata being saved as HDF5 attributes
was a unicode string. Specifically, for this case, it appears that the
`panel_id` key had a unicode `ff1` value.

Converting to a regular string fixes the issue.

I don't know why the panel ID came out to have a unicode value, but
we can guard against it and convert it into a regular string.

Signed-off-by: Patrick Avery <patrick.avery@kitware.com>